name = "zero-barriers-growth-accelerator"
compatibility_date = "2024-09-17"
main = "src/pages/_worker.js"

[env.production]
vars = { NODE_ENV = "production" }

[env.production.vars]
# These will be set in Cloudflare Pages dashboard
# OPENAI_API_KEY = "your-key-here"
# GEMINI_API_KEY = "your-key-here" 
# CLAUDE_API_KEY = "your-key-here"
